// Real AI-related bills being tracked across US state legislatures and Congress

export interface Bill {
  id: string;
  title: string;
  jurisdiction: string;
  billNumber: string;
  status: 'introduced' | 'committee' | 'passed-chamber' | 'enacted' | 'vetoed' | 'stalled';
  committee: string;
  summary: string;
  lastAction: string;
  lastActionDate: string;
  category: 'tax' | 'disclosure' | 'impact-assessment' | 'worker-protection';
  supporters: string[];
}

export const statusOrder: Record<string, number> = {
  enacted: 4,
  'passed-chamber': 3,
  committee: 2,
  introduced: 1,
  vetoed: 0,
  stalled: 0,
};

const bills: Bill[] = [
  {
    id: 'ca-sb1047',
    title: 'Safe and Secure Innovation for Frontier AI Models Act',
    jurisdiction: 'CA',
    billNumber: 'SB 1047',
    status: 'vetoed',
    committee: 'Senate Judiciary',
    summary:
      'Required safety testing for large AI models costing over $100M to train. Established liability for catastrophic harms and mandated kill switches.',
    lastAction: 'Vetoed by Governor Newsom',
    lastActionDate: '2024-09-29',
    category: 'impact-assessment',
    supporters: ['Scott Wiener', 'Yoshua Bengio', 'Geoffrey Hinton'],
  },
  {
    id: 'us-aida-2025',
    title: 'AI Disclosure Act of 2025',
    jurisdiction: 'US',
    billNumber: 'S. 401',
    status: 'committee',
    committee: 'Senate Commerce Committee',
    summary:
      'Requires companies to disclose when AI systems are used in hiring, lending, and insurance decisions. Mandates annual impact reports.',
    lastAction: 'Referred to subcommittee on Consumer Protection',
    lastActionDate: '2025-03-15',
    category: 'disclosure',
    supporters: ['Sen. Brian Schatz', 'Sen. John Kennedy'],
  },
  {
    id: 'ny-a7865',
    title: 'Automated Employment Decision Tools Law',
    jurisdiction: 'NY',
    billNumber: 'Local Law 144',
    status: 'enacted',
    committee: 'NYC City Council',
    summary:
      'Requires bias audits for AI hiring tools used in New York City. Companies must notify candidates when AI is used in employment decisions.',
    lastAction: 'Enforcement began',
    lastActionDate: '2023-07-05',
    category: 'disclosure',
    supporters: ['NYC Council', 'Laurie Cumbo'],
  },
  {
    id: 'eu-ai-act',
    title: 'EU Artificial Intelligence Act',
    jurisdiction: 'EU',
    billNumber: 'Reg. 2024/1689',
    status: 'enacted',
    committee: 'European Parliament',
    summary:
      'Comprehensive risk-based AI regulation. Bans social scoring, requires transparency for high-risk AI, and mandates conformity assessments.',
    lastAction: 'Entered into force',
    lastActionDate: '2024-08-01',
    category: 'impact-assessment',
    supporters: ['European Commission', 'Brando Benifei', 'Dragos Tudorache'],
  },
  {
    id: 'ca-ab2013',
    title: 'AI Training Data Transparency Act',
    jurisdiction: 'CA',
    billNumber: 'AB 2013',
    status: 'enacted',
    committee: 'Assembly Privacy & Consumer Protection',
    summary:
      'Requires AI developers to disclose training data sources on their websites, including data types, collection methods, and whether personal info is used.',
    lastAction: 'Signed by Governor Newsom',
    lastActionDate: '2024-09-28',
    category: 'disclosure',
    supporters: ['Ash Kalra', 'Electronic Frontier Foundation'],
  },
  {
    id: 'us-robot-tax-2025',
    title: 'Automation and AI Revenue Act',
    jurisdiction: 'US',
    billNumber: 'H.R. 1122',
    status: 'introduced',
    committee: 'House Ways and Means',
    summary:
      'Proposes a 2% tax on revenue generated by AI systems that displace human workers. Revenue funds job retraining programs and transition assistance.',
    lastAction: 'Introduced and referred to committee',
    lastActionDate: '2025-02-14',
    category: 'tax',
    supporters: ['Rep. Ro Khanna', 'Rep. Tim Ryan'],
  },
  {
    id: 'il-sb2979',
    title: 'Illinois AI Video Interview Act',
    jurisdiction: 'IL',
    billNumber: 'SB 2979',
    status: 'enacted',
    committee: 'Senate Labor',
    summary:
      'Requires employers to notify candidates when AI analyzes video interviews. Candidates must consent to AI analysis and can request deletion.',
    lastAction: 'Signed into law',
    lastActionDate: '2020-01-01',
    category: 'worker-protection',
    supporters: ['Sen. Cristina Castro'],
  },
  {
    id: 'wa-sb5838',
    title: 'Washington AI Task Force Act',
    jurisdiction: 'WA',
    billNumber: 'SB 5838',
    status: 'passed-chamber',
    committee: 'Senate Environment & Technology',
    summary:
      'Establishes a task force to study AI impact on state workforce and recommend policy frameworks including potential automation taxes.',
    lastAction: 'Passed Senate, referred to House Innovation committee',
    lastActionDate: '2025-03-22',
    category: 'impact-assessment',
    supporters: ['Sen. Joe Nguyen', 'Sen. Lisa Wellman'],
  },
  {
    id: 'nj-a4909',
    title: 'NJ Automated Decision-Making Accountability Act',
    jurisdiction: 'NJ',
    billNumber: 'A4909',
    status: 'committee',
    committee: 'Assembly Science & Technology',
    summary:
      'Requires impact assessments before deploying AI in government services. Mandates public disclosure of algorithmic decision-making criteria.',
    lastAction: 'Hearing scheduled in committee',
    lastActionDate: '2025-04-02',
    category: 'impact-assessment',
    supporters: ['Asm. Andrew Zwicker'],
  },
  {
    id: 'co-sb205',
    title: 'Colorado AI Consumer Protection Act',
    jurisdiction: 'CO',
    billNumber: 'SB 24-205',
    status: 'enacted',
    committee: 'Senate Business & Labor',
    summary:
      'Requires developers and deployers of high-risk AI to use reasonable care to avoid algorithmic discrimination. Mandates risk management and impact assessments.',
    lastAction: 'Signed by Governor Polis with statement',
    lastActionDate: '2024-05-17',
    category: 'worker-protection',
    supporters: ['Sen. Robert Rodriguez', 'Rep. Brianna Titone'],
  },
  {
    id: 'us-ai-worker-2025',
    title: 'AI Worker Protection and Transition Act',
    jurisdiction: 'US',
    billNumber: 'S. 892',
    status: 'introduced',
    committee: 'Senate HELP Committee',
    summary:
      'Requires 90-day notice before AI-driven layoffs affecting 50+ workers. Mandates severance packages funded by automation savings and retraining credits.',
    lastAction: 'Introduced with 8 cosponsors',
    lastActionDate: '2025-03-08',
    category: 'worker-protection',
    supporters: ['Sen. Sherrod Brown', 'Sen. Bob Casey'],
  },
  {
    id: 'ma-h4197',
    title: 'Massachusetts AI Taxation Study Commission',
    jurisdiction: 'MA',
    billNumber: 'H.4197',
    status: 'committee',
    committee: 'Joint Committee on Revenue',
    summary:
      'Establishes a commission to study the feasibility of taxing AI-generated revenue and automation to fund public services and worker transition programs.',
    lastAction: 'Extended deadline for committee report',
    lastActionDate: '2025-03-30',
    category: 'tax',
    supporters: ['Rep. Dylan Fernandes', 'Rep. Jack Lewis'],
  },
];

export function getActiveBills(): Bill[] {
  return bills.filter((b) => b.status !== 'stalled');
}
